[package]
name = "rustnpp"
version = "1.0.0"
authors = ["ნიკა <nika.begiashvili@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
libc="0.2.153"
winapi = { version = "0.3.9", features = ["std","minwindef","windef","winuser"] }
lazy_static = "1.4.0"
#user32-sys = "0.2.0"